### ISSUE TITLE
ETCS under construction

### ISSUE THREAD

**Issue by Nakaner** [OpenRailwayMap/OpenRailwayMap-CartoCSS#10]
![etcs-under-construction](https://user-images.githubusercontent.com/3611273/69139493-eb8b6080-0ac0-11ea-9bd7-555490919791.png)

ETCS under construction (`construction:railway:etcs=*`) is supported by the MapCSS style.

See also https://github.com/OpenRailwayMap/OpenRailwayMap/pull/662

**Comment by mmosteck** [comment]
I would also suggest implementing a distinction between ETCS levels (at least 1 and 2, LS and 3 could come later) since on most lines the data is already there (e.g "construction:railway:etcs" : "2" instead of "construction:railway:etcs":"yes") and it just needs proper style.
Is my proposed color (#87cefa) readable on tiles? I couldn't test it.
