### ISSUE TITLE
Absence of train protection - SQL condition not respected

### ISSUE THREAD

**Issue by davide84** [OpenRailwayMap/OpenRailwayMap-CartoCSS#85]
Hi,

after implementing the SCMT train protection system I have noticed that the lines where 'railway:scmt=no' are not drawn in black, as they should be, but in grey instead ("no information available").

It seems to me that the following condition in functions.sql is somehow not respected:
`IF (pzb = 'no' AND lzb = 'no' AND etcs = 'no') OR (atb = 'no' AND etcs = 'no') OR (scmt = 'no' AND etcs = 'no') THEN`
particularly the third OR is ignored.
Of course I checked that both etcs and scmt tags are 'no'.

Assuming the database is synchronized, on my local instance of kosmtik the lines are correctly drawn in black.
I don't think it is an issue regarding the delay in the rendering, because other changes have appeared in ORM online as well, but no line is drawn in black.
And I've seen that elsewhere in Europe, only lines with etcs=no & lzb=no & pzb=no are drawn in black.

Here an example from the area of Udine, a city in North-East of Italy, first image is my local renderer:

![Screenshot from 2022-10-22 19-43-16](https://user-images.githubusercontent.com/21276516/197355225-a94f4485-8005-4fb7-b7a7-a69be01a283b.png)

![Screenshot from 2022-10-22 19-42-50](https://user-images.githubusercontent.com/21276516/197355228-6eb6ef9f-7770-4259-b93f-e31a6f7a25c9.png)

**Comment by Nakaner** [comment]
The reason was that functions.sql was not rerun after the style upgrade. I rerun `sql/functions.sql` on the server to resolve the issue. This is addressed by https://github.com/OpenRailwayMap/server-admin/commit/b9c9a7fc354cc8e7500cff603e829ee29fddfa9c

https://tiles.openrailwaymap.org/signals/15/17590/11649.png freshly from the tile server:

![tile](https://user-images.githubusercontent.com/3611273/197384695-5ff9a3b6-93a6-45e6-99e1-72718476e7b6.png)
